# Generated by Django 5.2.3 on 2025-07-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='uploads/product/default.png', upload_to='uploads/product/'),
        ),
    ]
