# Generated by Django 5.2.4 on 2025-07-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_state',
            field=models.CharField(default=7, max_length=25),
            preserve_default=False,
        ),
    ]
